"""The canonical OHLC bar — specs/03-market-data.md and ADR 0004.

Time semantics, restated because everything downstream depends on them:

* `start_time_utc` is the instant the aggregation window **opens**.
* The window is half-open, `[start_time_utc, end_time_utc)`. A print exactly at
  `end_time_utc` belongs to the next bar.
* `end_time_utc` is stored, not derived, because a session-close bar is
  truncated and a `1D` bar spans a session rather than a calendar day.
* Never infer a bar's duration from its timeframe. Ask the bar.

Price fields are annotated `Decimal` because that is what they are once the bar
exists. `__post_init__` also accepts `str`/`int` and quantizes them, so an
adapter can hand over provider text directly without a conversion dance.
"""

from __future__ import annotations

import dataclasses
from collections.abc import Sequence
from datetime import date, datetime, timedelta
from decimal import Decimal
from enum import Enum
from typing import Any, Self

from alphagate.core.errors import InvariantViolation
from alphagate.core.identifiers import Ticker
from alphagate.core.numeric import price, quantity
from alphagate.core.time_model import SessionKind, Timeframe, ensure_utc

__all__ = ["AdjustmentMode", "Bar", "BarKey", "Feed", "closed_bars"]


class Feed(Enum):
    """Which data feed a bar's prints came from.

    Part of a bar's identity: the same window on IEX and on SIP are different
    observations, not duplicates of one another.
    """

    IEX = "IEX"
    SIP = "SIP"
    OTC = "OTC"
    SYNTHETIC = "SYNTHETIC"
    """Generated by a fake provider or a replay fixture, never by a market."""


class AdjustmentMode(Enum):
    """Whether the series is adjusted for corporate actions.

    Also part of identity. Mixing the two silently is how a split turns into a
    fake breakout.
    """

    UNADJUSTED = "UNADJUSTED"
    ADJUSTED = "ADJUSTED"


type BarKey = tuple[Ticker, Timeframe, datetime, Feed, AdjustmentMode]
"""The canonical uniqueness tuple (specs/12-storage.md)."""


@dataclasses.dataclass(frozen=True, slots=True)
class Bar:
    symbol: Ticker
    timeframe: Timeframe
    start_time_utc: datetime
    end_time_utc: datetime
    session_date: date
    session: SessionKind
    open: Decimal
    high: Decimal
    low: Decimal
    close: Decimal
    volume: Decimal
    source: str
    feed: Feed
    adjustment_mode: AdjustmentMode
    is_final: bool
    vwap: Decimal | None = None
    trade_count: int | None = None
    revision: int = 0

    def __post_init__(self) -> None:
        self._normalize_times()
        self._normalize_prices()
        self._check_ohlc()
        self._check_counters()

    # -- construction ------------------------------------------------------

    def _normalize_times(self) -> None:
        start = ensure_utc(self.start_time_utc, field="start_time_utc")
        end = ensure_utc(self.end_time_utc, field="end_time_utc")
        object.__setattr__(self, "start_time_utc", start)
        object.__setattr__(self, "end_time_utc", end)

        if end <= start:
            raise InvariantViolation(
                f"end_time_utc ({end.isoformat()}) must follow start_time_utc ({start.isoformat()})"
            )
        span = end - start
        if span > self.timeframe.nominal_duration:
            raise InvariantViolation(
                f"bar spans {span}, exceeding the nominal duration "
                f"{self.timeframe.nominal_duration} of {self.timeframe.code}"
            )

    def _normalize_prices(self) -> None:
        for field in ("open", "high", "low", "close"):
            value = price(getattr(self, field), field=field)
            if value <= 0:
                raise InvariantViolation(f"{field}: price must be positive, got {value}")
            object.__setattr__(self, field, value)

        volume = quantity(self.volume, field="volume")
        if volume < 0:
            raise InvariantViolation(f"volume: must not be negative, got {volume}")
        object.__setattr__(self, "volume", volume)

        if self.vwap is not None:
            object.__setattr__(self, "vwap", price(self.vwap, field="vwap"))

    def _check_ohlc(self) -> None:
        if self.high < self.low:
            raise InvariantViolation(f"high ({self.high}) must be at least low ({self.low})")
        if self.high < max(self.open, self.close):
            raise InvariantViolation(f"high ({self.high}) must be at least max(open, close)")
        if self.low > min(self.open, self.close):
            raise InvariantViolation(f"low ({self.low}) must be at most min(open, close)")
        if self.vwap is not None and not (self.low <= self.vwap <= self.high):
            raise InvariantViolation(f"vwap ({self.vwap}) must lie within [low, high]")

    def _check_counters(self) -> None:
        if self.trade_count is not None and self.trade_count < 0:
            raise InvariantViolation(f"trade_count: must not be negative, got {self.trade_count}")
        if self.revision < 0:
            raise InvariantViolation(f"revision: must not be negative, got {self.revision}")

    # -- identity ----------------------------------------------------------

    @property
    def key(self) -> BarKey:
        """Logical identity.

        Deliberately excludes `revision`: a corrected bar replaces its
        predecessor rather than joining it.
        """
        return (
            self.symbol,
            self.timeframe,
            self.start_time_utc,
            self.feed,
            self.adjustment_mode,
        )

    # -- window ------------------------------------------------------------

    @property
    def duration(self) -> timedelta:
        return self.end_time_utc - self.start_time_utc

    @property
    def is_truncated(self) -> bool:
        """Whether the bar is shorter than its timeframe's grid step.

        True for the last bar of a session, and for every `1D`/`1W` bar, which
        span a session rather than a calendar period (ADR 0004 D5/D6).
        """
        return self.duration < self.timeframe.nominal_duration

    def contains(self, instant: datetime) -> bool:
        """Half-open membership: `start <= instant < end`."""
        moment = ensure_utc(instant, field="instant")
        return self.start_time_utc <= moment < self.end_time_utc

    # -- transitions -------------------------------------------------------

    def finalized(self) -> Self:
        """Return the finalized counterpart of a partial bar.

        Refuses to re-finalize: a closed bar being closed again means the caller
        lost track of the stream, and allowing it silently is how a look-ahead
        bug hides.
        """
        if self.is_final:
            raise InvariantViolation(f"{self.key}: bar is already final")
        return dataclasses.replace(self, is_final=True)

    def revised(self, **changes: Any) -> Self:
        """Return a corrected bar with the revision counter bumped.

        Identity-defining fields are rejected: changing one produces a different
        bar, not a revision of this one.
        """
        forbidden = {"symbol", "timeframe", "start_time_utc", "feed", "adjustment_mode", "revision"}
        if overlap := forbidden & changes.keys():
            raise InvariantViolation(f"revised() cannot change identity fields: {sorted(overlap)}")
        return dataclasses.replace(self, revision=self.revision + 1, **changes)


def closed_bars(bars: Sequence[Bar]) -> tuple[Bar, ...]:
    """The bars an engine may consume: the ones that have closed.

    A window that ends at "now" ends on a bar that is still trading, because
    that is what a provider returns. Drawing it is right; deriving from it is
    not — its close is not a close, and an indicator, a swing or an alert built
    on one answers differently depending on the second the request arrived
    (`specs/03-market-data.md`, CLAUDE.md §11/§12).

    A filter rather than a truncation: a partial bar in the middle of a series
    is a provider fault, not a boundary, and silently keeping everything after
    it would hide that.
    """
    return tuple(bar for bar in bars if bar.is_final)
